import { createThemedStyles, getTileColor, getTileBadgeColor, isDarkMode } from '../theme';
import {
  GAP,
  CHART_HEIGHT,
  BAR_WIDTH,
  ROW_HEIGHT,
  ROW_GAP,
  PART_ROW_HEIGHT,
} from './utils';

const styles = createThemedStyles((colors) => ({
  screen: { flex: 1, backgroundColor: colors.bg },
  content: { padding: 14, paddingTop: 8, paddingBottom: 40, width: '100%', maxWidth: 460, alignSelf: 'center' },
  contentWithSheet: { paddingBottom: 260 },
  title: { fontSize: 26, fontWeight: '800', color: colors.text, marginBottom: 4 },
  homeHead: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 4 },
  titleRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 4 },
  titleEmoji: { fontSize: 26 },
  sub: { fontSize: 14, color: colors.textSoft, marginBottom: 18 },
  back: { paddingVertical: 6, marginBottom: 2, alignSelf: 'flex-start' },
  backText: { fontSize: 16, fontWeight: '800', color: colors.primary },
  // Body weight panel（页面底部常驻）
  bwPanel: { backgroundColor: colors.card, borderRadius: 18, padding: 14, marginTop: 8, marginBottom: 16 },
  bwHead: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 12 },
  bwTitle: { fontSize: 15, fontWeight: '800', color: colors.text },
  bwRow: { backgroundColor: getTileColor('#DCD3F2'), marginTop: 0 },
  bwRowGrid: { marginTop: 8 },
  bwHistTitle: { fontSize: 15, fontWeight: '800', color: colors.text, marginBottom: 4 },
  bwEmpty: { fontSize: 13, color: colors.textSoft, marginTop: 2 },
  bwInputRow: { flexDirection: 'row', gap: 10, marginBottom: 10 },
  bwInput: {
    flex: 1, backgroundColor: colors.bg, borderRadius: 12, paddingHorizontal: 14,
    paddingVertical: 10, fontSize: 15, color: colors.text,
  },
  bwAddBtn: { backgroundColor: colors.primary, borderRadius: 12, paddingHorizontal: 18, alignItems: 'center', justifyContent: 'center' },
  bwAddText: { color: colors.white, fontSize: 14, fontWeight: '800' },
  bwStatsRow: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  bwLast: { fontSize: 14, fontWeight: '800', color: colors.text },
  bwDelta: { fontSize: 13, fontWeight: '800' },
  bwQuickBox: {
    backgroundColor: colors.bg, borderRadius: 16,
    padding: 12, marginBottom: 12,
  },
  bwSheetHistory: { marginTop: 2 },
  bwItem: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between',
    paddingVertical: 8, borderTopWidth: 1, borderTopColor: colors.line,
  },
  bwItemDay: { fontSize: 13, color: colors.textSoft },
  bwItemVal: { fontSize: 14, fontWeight: '800', color: colors.text, flex: 1, textAlign: 'right', marginRight: 12 },
  bwItemDel: { fontSize: 14, color: colors.textSoft, paddingHorizontal: 6 },

  // Part list
  partRow: {
    flexDirection: 'row', alignItems: 'center', borderRadius: 18,
    height: PART_ROW_HEIGHT, paddingHorizontal: 18, marginBottom: GAP,
  },
  partRowMoving: { borderWidth: 2, borderColor: colors.primary, opacity: 0.96 },
  partEmoji: { fontSize: 28, marginRight: 14 },
  partLabel: { fontSize: 18, fontWeight: '800', color: colors.text, flex: 1 },
  partBadge: {
    backgroundColor: getTileBadgeColor(), borderRadius: 12,
    paddingHorizontal: 10, paddingVertical: 4, marginRight: 8,
  },
  partBadgeText: { fontSize: 12, fontWeight: '800', color: colors.text },
  partArrow: { fontSize: 24, fontWeight: '800', color: colors.text, opacity: 0.4 },
  partGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: GAP, marginBottom: 6 },
  partTile: {
    aspectRatio: 1,
    borderRadius: 18,
    padding: 14,
    justifyContent: 'center',
    alignItems: 'center',
  },
  partTileEmoji: { fontSize: 32, marginBottom: 10 },
  partTileLabel: { fontSize: 18, fontWeight: '900', color: colors.text },

  // Stats（首页缩小版）
  statsCard: {
    backgroundColor: colors.card,
    borderRadius: 18,
    padding: 14,
    marginTop: 10,
    marginBottom: 12,
  },
  statsCardCompact: { paddingVertical: 12 },
  statsHead: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 8 },
  statsTitle: { fontSize: 15, fontWeight: '800', color: colors.text },
  statsRange: { fontSize: 12, fontWeight: '800', color: colors.textSoft },
  statsEmpty: { fontSize: 13, color: colors.textSoft, lineHeight: 20, marginTop: 4 },
  statsGrid: { flexDirection: 'row', gap: 8 },
  statsGridCompact: { flexDirection: 'row', gap: 8 },
  statBox: {
    flex: 1,
    backgroundColor: colors.bg,
    borderRadius: 14,
    paddingVertical: 10,
    paddingHorizontal: 8,
    minHeight: 78,
  },
  statBoxCompact: {
    flex: 1,
    backgroundColor: colors.bg,
    borderRadius: 12,
    paddingVertical: 8,
    paddingHorizontal: 8,
    minHeight: 64,
  },
  statValue: { fontSize: 20, fontWeight: '900', color: colors.text },
  statLabel: { fontSize: 11, fontWeight: '800', color: colors.textSoft, marginTop: 2 },
  statDelta: { fontSize: 10, fontWeight: '700', color: colors.primary, marginTop: 4 },
  statsFoot: { marginTop: 12, borderTopWidth: 1, borderTopColor: colors.line, paddingTop: 9, gap: 4 },
  statsFootCompact: { marginTop: 10, borderTopWidth: 1, borderTopColor: colors.line, paddingTop: 8, gap: 3 },
  recordText: { fontSize: 12, fontWeight: '700', color: colors.textSoft },
  statsBwLine: {
    marginTop: 10,
    fontSize: 12,
    fontWeight: '700',
    color: colors.textSoft,
  },
  progressSection: {
    marginTop: 14,
    borderTopWidth: 1,
    borderTopColor: colors.line,
    paddingTop: 12,
  },
  progressSectionTitle: { fontSize: 15, fontWeight: '800', color: colors.text },
  progressSectionHint: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.textSoft,
    marginTop: 2,
    marginBottom: 10,
  },
  progressFilters: { flexDirection: 'row', gap: 8, marginBottom: 10 },
  progressFilterBtn: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: colors.bg,
  },
  progressFilterBtnOn: { backgroundColor: colors.primarySoft },
  progressFilterText: { fontSize: 12, fontWeight: '800', color: colors.textSoft },
  progressFilterTextOn: { color: colors.primary },
  progressList: { gap: 6 },
  progressRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.bg,
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 12,
    gap: 10,
  },
  progressRowOn: {
    borderWidth: 1.5,
    borderColor: colors.primary,
    backgroundColor: colors.primarySoft,
  },
  progressRowMain: { flex: 1, minWidth: 0 },
  progressName: { fontSize: 14, fontWeight: '800', color: colors.text },
  progressMeta: { fontSize: 11, fontWeight: '700', color: colors.textSoft, marginTop: 2 },
  progressChartBox: { marginTop: 12 },
  progressChartTitle: {
    fontSize: 13,
    fontWeight: '800',
    color: colors.text,
    marginBottom: 8,
  },

  // Level 2 header
  l2Header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 2 },
  l2Actions: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  layoutBtn: {
    width: 34, height: 34, borderRadius: 17,
    backgroundColor: colors.card, borderWidth: 1.5, borderColor: colors.line,
    alignItems: 'center', justifyContent: 'center',
  },
  layoutBtnActive: { backgroundColor: colors.primarySoft, borderColor: colors.primary },
  layoutBtnText: { fontSize: 18, fontWeight: '900', color: colors.textSoft, lineHeight: 20 },
  layoutBtnTextActive: { color: colors.primary },
  editBtn: {
    paddingHorizontal: 14, paddingVertical: 6, borderRadius: 14,
    backgroundColor: colors.card, borderWidth: 1.5, borderColor: colors.line,
  },
  editBtnActive: { backgroundColor: colors.primary, borderColor: colors.primary },
  editBtnText: { fontSize: 13, fontWeight: '800', color: colors.textSoft },
  editBtnTextActive: { color: colors.white },

  // Exercise list
  exRow: {
    flexDirection: 'row', alignItems: 'center', backgroundColor: colors.card,
    borderRadius: 16, paddingVertical: 14, paddingHorizontal: 16, marginBottom: ROW_GAP,
    height: ROW_HEIGHT,
  },
  exRowMoving: { borderWidth: 2, borderColor: colors.primary, backgroundColor: colors.primarySoft },
  exTap: { flex: 1, flexDirection: 'row', alignItems: 'center' },
  exMain: { flex: 1, minWidth: 0, paddingRight: 8 },
  exName: { fontSize: 16, fontWeight: '700', color: colors.text },
  exCnt: { fontSize: 13, color: colors.textSoft, marginRight: 8 },
  exProgress: { alignItems: 'flex-end', maxWidth: 168 },
  exProgressMain: { fontSize: 13, fontWeight: '900', color: colors.text, marginTop: 2 },
  exProgressSub: { fontSize: 11, fontWeight: '800', color: colors.primary, marginTop: 2 },
  exProgressDetail: { fontSize: 11, fontWeight: '700', color: colors.textSoft, marginTop: 3 },
  sparkWrap: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'flex-end',
    gap: 2,
  },
  sparkBar: {
    borderRadius: 2,
    minHeight: 3,
  },
  exGrip: {
    width: 32, height: 32, borderRadius: 8, backgroundColor: colors.bg,
    alignItems: 'center', justifyContent: 'center', marginRight: 10,
    cursor: 'grab',
  },
  exGripText: { fontSize: 18, color: colors.textSoft },
  exDel: { width: 28, height: 28, borderRadius: 14, alignItems: 'center', justifyContent: 'center', marginLeft: 6 },
  exDelText: { fontSize: 16, color: colors.danger, fontWeight: '700' },
  exEmpty: { fontSize: 14, color: colors.textSoft, marginTop: 4, marginBottom: 8 },
  exerciseGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: GAP, marginBottom: 2 },
  exerciseTile: {
    aspectRatio: 1,
    backgroundColor: colors.card,
    borderRadius: 18,
    padding: 12,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 6,
  },
  tileDragging: { opacity: 0.9, transform: [{ scale: 1.06 }] },
  exerciseTileEmoji: { fontSize: 24 },
  exerciseTileName: { fontSize: 15, fontWeight: '800', color: colors.text, lineHeight: 19, textAlign: 'center' },
  exerciseTileMeta: { gap: 2, alignItems: 'center' },
  exerciseTileMain: { fontSize: 12, fontWeight: '900', color: colors.text },
  exerciseTileSub: { fontSize: 11, fontWeight: '800', color: colors.textSoft },
  addExerciseBtn: {
    borderRadius: 14,
    paddingVertical: 13,
    alignItems: 'center',
    marginTop: 8,
    backgroundColor: colors.card,
    borderWidth: 2,
    borderColor: colors.line,
    borderStyle: 'dashed',
  },
  addExerciseText: { fontSize: 15, fontWeight: '800', color: colors.textSoft },

  // Record sets
  logCard: { backgroundColor: colors.card, borderRadius: 22, padding: 16, marginBottom: 24 },
  setRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 12 },
  setNo: {
    width: 26, height: 26, borderRadius: 13, backgroundColor: colors.primarySoft, color: colors.primary,
    textAlign: 'center', lineHeight: 26, fontWeight: '800', fontSize: 13, marginRight: 10,
  },
  setInput: {
    width: 68, backgroundColor: colors.bg, borderRadius: 12, paddingVertical: 10,
    textAlign: 'center', fontSize: 16, fontWeight: '700', color: colors.text,
  },
  setUnit: { marginHorizontal: 8, fontSize: 14, color: colors.textSoft, fontWeight: '700' },
  setSimpleText: { flex: 1, fontSize: 14, color: colors.textSoft, fontWeight: '800' },
  setDel: { marginLeft: 'auto', padding: 6 },
  setDelText: { fontSize: 16, color: colors.textSoft },
  addSet: {
    borderRadius: 14, paddingVertical: 12, alignItems: 'center', marginBottom: 12,
    borderWidth: 2, borderColor: colors.line, borderStyle: 'dashed',
  },
  addSetText: { fontSize: 15, fontWeight: '800', color: colors.textSoft },
  saveBtn: {
    backgroundColor: colors.line, borderRadius: 16, paddingVertical: 15, alignItems: 'center',
  },
  saveBtnActive: { backgroundColor: colors.primary },
  saveBtnText: { color: colors.white, fontSize: 16, fontWeight: '800' },
  saveBtnTextDisabled: { opacity: 0.5 },

  // Quick record sheet
  sheetOverlay: {
    position: 'absolute', left: 0, right: 0, top: 0, bottom: 0,
    justifyContent: 'flex-end', zIndex: 50,
  },
  sheetBackdrop: {
    position: 'absolute', left: 0, right: 0, top: 0, bottom: 0,
    backgroundColor: isDarkMode() ? 'rgba(0,0,0,0.45)' : 'rgba(74,64,56,0.16)',
  },
  sheetKeyboard: { flex: 1, width: '100%', justifyContent: 'flex-end' },
  sheetCard: {
    width: '100%', maxWidth: 520, alignSelf: 'center',
    maxHeight: '82%', backgroundColor: colors.card,
    borderTopLeftRadius: 22, borderTopRightRadius: 22,
    paddingHorizontal: 14, paddingTop: 8, paddingBottom: 12,
  },
  sheetHandle: {
    width: 42, height: 4, borderRadius: 2, backgroundColor: colors.line,
    alignSelf: 'center', marginBottom: 10,
  },
  sheetHead: { flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 10 },
  sheetTitleRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  sheetTitle: { fontSize: 20, fontWeight: '800', color: colors.text },
  sheetTitleEdit: {
    fontSize: 12, fontWeight: '800', color: colors.primary,
    backgroundColor: colors.primarySoft, borderRadius: 10,
    paddingHorizontal: 8, paddingVertical: 2,
  },
  sheetSub: { fontSize: 12, color: colors.textSoft, fontWeight: '700', marginTop: 2 },
  sheetClose: {
    width: 34, height: 34, borderRadius: 17, backgroundColor: colors.bg,
    alignItems: 'center', justifyContent: 'center',
  },
  sheetCloseText: { fontSize: 16, color: colors.textSoft, fontWeight: '800' },
  sheetScroll: { maxHeight: 430, flexShrink: 1 },
  // 键盘弹起时：面板占满剩余空间，内部滚动区收缩，保证输入行和保存按钮都可见
  sheetCardLifted: { maxHeight: '100%' },
  bwSheetCard: { maxHeight: '92%' },
  bwSheetScroll: { maxHeight: 560, flexShrink: 1 },
  sheetScrollContent: { paddingBottom: 6 },
  sheetHistTitle: { fontSize: 14, fontWeight: '800', color: colors.textSoft, marginTop: 8 },
  sheetSave: {
    marginTop: 10, backgroundColor: colors.line, borderRadius: 16,
    paddingVertical: 15, alignItems: 'center',
  },
  sheetSaveActive: { backgroundColor: colors.primary },
  sheetSaveText: { color: colors.white, fontSize: 16, fontWeight: '800' },
  createSheetCard: { maxHeight: '90%' },
  createScroll: { flexShrink: 1 },
  createScrollContent: { paddingBottom: 4 },
  createInput: {
    backgroundColor: colors.bg,
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 16,
    fontWeight: '800',
    color: colors.text,
    marginBottom: 12,
  },
  createModeGrid: { gap: 8 },
  createCountRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.bg,
    borderRadius: 14,
    padding: 12,
    borderWidth: 1.5,
    borderColor: colors.line,
  },
  createCountStepper: { width: 120 },
  createModeItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.bg,
    borderRadius: 14,
    padding: 12,
    borderWidth: 1.5,
    borderColor: colors.line,
  },
  createModeItemOn: { borderColor: colors.primary, backgroundColor: colors.primarySoft },
  createModeCheck: {
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: colors.card,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  createModeCheckOn: { backgroundColor: colors.primary },
  createModeCheckText: { fontSize: 14, fontWeight: '900', color: colors.textSoft },
  createModeCheckTextOn: { color: colors.white },
  createModeTitle: { fontSize: 15, fontWeight: '800', color: colors.text },
  createModeSub: { fontSize: 12, fontWeight: '700', color: colors.textSoft, marginTop: 2 },
  datePickBtn: {
    flexDirection: 'row', alignItems: 'center',
    backgroundColor: colors.bg, borderRadius: 14,
    paddingHorizontal: 12, paddingVertical: 11,
    marginBottom: 10,
  },
  datePickLabel: { fontSize: 12, fontWeight: '800', color: colors.textSoft, marginRight: 10 },
  datePickText: { flex: 1, fontSize: 15, fontWeight: '800', color: colors.text },
  datePickArrow: { fontSize: 11, fontWeight: '800', color: colors.textSoft },
  sheetCalendarWrap: { marginBottom: 10 },
  quickSetRow: {
    flexDirection: 'row', alignItems: 'center',
    backgroundColor: colors.bg, borderRadius: 16,
    padding: 10, marginBottom: 10, gap: 8,
  },
  quickSetNo: {
    width: 26, height: 26, borderRadius: 13,
    backgroundColor: colors.primarySoft, color: colors.primary,
    textAlign: 'center', lineHeight: 26, fontWeight: '800', fontSize: 13,
  },
  quickField: { flex: 1, minWidth: 0 },
  quickLabel: { fontSize: 11, color: colors.textSoft, fontWeight: '800', marginBottom: 5, textAlign: 'center' },
  quickSimpleText: { flex: 1, fontSize: 14, color: colors.textSoft, fontWeight: '800', textAlign: 'center' },
  stepper: {
    flexDirection: 'row', alignItems: 'center',
    backgroundColor: colors.card, borderRadius: 13,
    borderWidth: 1, borderColor: colors.line,
    overflow: 'hidden',
  },
  stepperBtn: {
    width: 34, height: 40, alignItems: 'center', justifyContent: 'center',
    backgroundColor: colors.primarySoft,
  },
  stepperBtnText: { fontSize: 20, color: colors.primary, fontWeight: '900', lineHeight: 22 },
  stepperInput: {
    flex: 1, minWidth: 38, height: 40, paddingHorizontal: 4,
    textAlign: 'center', fontSize: 16, fontWeight: '800', color: colors.text,
  },
  quickDel: {
    width: 28, height: 40, alignItems: 'center', justifyContent: 'center',
  },
  quickDelText: { fontSize: 15, color: colors.textSoft, fontWeight: '800' },
  quickAddSet: {
    borderRadius: 14, paddingVertical: 11, alignItems: 'center', marginBottom: 8,
    borderWidth: 2, borderColor: colors.line, borderStyle: 'dashed',
  },
  quickAddSetText: { fontSize: 14, fontWeight: '800', color: colors.textSoft },

  // Single-row record
  recordPanel: {
    flexDirection: 'row', alignItems: 'flex-start', gap: 10,
    backgroundColor: colors.bg, borderRadius: 16, padding: 12, marginBottom: 10,
  },
  recordField: { flex: 1, minWidth: 0 },
  recordFieldLabel: { fontSize: 11, color: colors.textSoft, fontWeight: '800', marginBottom: 6, textAlign: 'center' },
  recordSimpleHint: {
    fontSize: 14, color: colors.textSoft, fontWeight: '800', textAlign: 'center',
    backgroundColor: colors.bg, borderRadius: 16, padding: 18, marginBottom: 10,
  },

  // Chart
  chartWrap: { backgroundColor: colors.card, borderRadius: 18, padding: 14, marginBottom: 14 },
  chartWrapEmbedded: {
    backgroundColor: colors.bg,
    marginBottom: 0,
    padding: 12,
  },
  chartHead: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 6,
    gap: 8,
  },
  chartLabel: { fontSize: 13, fontWeight: '800', color: colors.textSoft, flex: 1 },
  chartPace: { fontSize: 11, fontWeight: '700', color: colors.primary, marginBottom: 8 },
  chartToggle: {
    flexDirection: 'row',
    backgroundColor: colors.bg,
    borderRadius: 999,
    padding: 2,
  },
  chartToggleBtn: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 999,
  },
  chartToggleBtnOn: { backgroundColor: colors.primarySoft },
  chartToggleText: { fontSize: 11, fontWeight: '800', color: colors.textSoft },
  chartToggleTextOn: { color: colors.primary },
  chartBox: { flexDirection: 'row', alignItems: 'flex-end' },
  chartYMax: { fontSize: 10, color: colors.textSoft, fontWeight: '700', marginRight: 6, marginBottom: 14 },
  chartBars: { flex: 1, flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-around', height: CHART_HEIGHT },
  chartCol: { alignItems: 'center', width: BAR_WIDTH },
  chartVal: { fontSize: 10, fontWeight: '700', color: colors.text, marginBottom: 3 },
  chartBar: { width: BAR_WIDTH - 8, borderRadius: 6, minHeight: 4 },
  chartDay: { fontSize: 9, color: colors.textSoft, marginTop: 4 },

  // History
  histTitle: { fontSize: 18, fontWeight: '800', color: colors.text, marginBottom: 4 },
  histEmpty: { fontSize: 14, color: colors.textSoft, marginTop: 10, lineHeight: 20 },
  histCard: { backgroundColor: colors.card, borderRadius: 18, padding: 14, marginTop: 10 },
  histHead: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8 },
  histDay: { fontSize: 14, fontWeight: '800', color: colors.text },
  histTopWrap: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  histTop: { fontSize: 13, fontWeight: '800', color: colors.text },
  histTrend: { fontSize: 12, fontWeight: '800' },
  histSets: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  histSet: { backgroundColor: colors.bg, borderRadius: 10, paddingVertical: 6, paddingHorizontal: 10 },
  histSetText: { fontSize: 13, fontWeight: '700', color: colors.text },
  histVol: { fontSize: 12, color: colors.textSoft, marginTop: 8 },
  histActions: { flexDirection: 'row', gap: 14, marginTop: 10, borderTopWidth: 1, borderTopColor: colors.line, paddingTop: 10 },
  histActBtn: { paddingHorizontal: 4, paddingVertical: 2 },
  histActText: { fontSize: 13, fontWeight: '800', color: colors.primary },
  histCompactList: { marginTop: 4, borderTopWidth: 1, borderTopColor: colors.line },
  histCompactRow: {
    flexDirection: 'row', alignItems: 'center',
    paddingVertical: 8, borderBottomWidth: 1, borderBottomColor: colors.line,
  },
  histCompactMain: { flex: 1, minWidth: 0, paddingRight: 8 },
  histCompactHead: { fontSize: 12, fontWeight: '800', color: colors.text },
  histCompactSets: { fontSize: 12, color: colors.textSoft, marginTop: 2 },
  histCompactActions: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  histCompactAction: { fontSize: 12, fontWeight: '800', color: colors.primary },

  // Edit modal
  modalOverlay: {
    position: 'absolute', top: 0, left: 0, right: 0, bottom: 0,
    alignItems: 'center', justifyContent: 'center', padding: 14, zIndex: 100,
  },
  modalBackdrop: {
    position: 'absolute', top: 0, left: 0, right: 0, bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.35)',
  },
  modalCard: { backgroundColor: colors.card, borderRadius: 22, padding: 18, width: '100%', maxWidth: 420 },
  modalTitle: { fontSize: 18, fontWeight: '800', color: colors.text, marginBottom: 4 },
  modalSub: { fontSize: 13, fontWeight: '700', color: colors.textSoft, marginBottom: 12 },
  modalLabel: { fontSize: 13, fontWeight: '800', color: colors.textSoft, marginBottom: 6, marginTop: 4 },
  modalTimeRow: { flexDirection: 'row', gap: 10, marginBottom: 10 },
  modalDateInput: {
    flex: 1.4, backgroundColor: colors.bg, borderRadius: 12, paddingHorizontal: 12,
    paddingVertical: 10, fontSize: 14, color: colors.text,
  },
  modalDateBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  modalDateText: { fontSize: 14, color: colors.text, fontWeight: '700' },
  modalDateArrow: { fontSize: 11, color: colors.textSoft, fontWeight: '800' },
  modalTimeInput: {
    flex: 1, backgroundColor: colors.bg, borderRadius: 12, paddingHorizontal: 12,
    paddingVertical: 10, fontSize: 14, color: colors.text,
  },
  modalCalendarWrap: { marginBottom: 8 },
  modalBtns: { flexDirection: 'row', gap: 10, marginTop: 6 },
  modalBtn: { flex: 1, paddingVertical: 12, borderRadius: 14, alignItems: 'center' },
  modalBtnGhost: { backgroundColor: colors.bg },
  modalBtnGhostText: { fontSize: 15, fontWeight: '800', color: colors.textSoft },
  modalBtnPrimary: { backgroundColor: colors.primary },
  modalBtnPrimaryText: { fontSize: 15, fontWeight: '800', color: colors.white },

}));

export default styles;

